name: CI Pipeline for My App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-first-app:${{ github.sha }}

      - name: Checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: rohyoungjoo/my-first-app-manifests
          token: ${{ secrets.PAT_TOKEN }}
          path: 'manifests'

      - name: Update Kubernetes manifest
        run: |
          sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/my-first-app:${{ github.sha }}|g' manifests/deployment.yaml

      - name: Commit and push changes
        run: |
          cd manifests
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
